# Generated by Django 2.1.5 on 2019-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190513_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
