# Generated by Django 2.1.5 on 2019-05-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_testmodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
