# Generated by Django 2.1.5 on 2019-05-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190513_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
