# Generated by Django 2.1.5 on 2019-05-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='view_count',
            field=models.IntegerField(),
        ),
    ]
